# 1. Set your GitHub default branch to dev/develop
# 2. In annotatevcf project settings->advanced set:
#    - GitHub Status Updates (this should be on already)
#    - Only build pull requests
#    - Auto-cancel redundant builds
#    - Free and Open Source (this should be on already)

version: 2.1
jobs:
  license_chk:
    machine:
      # need machine as want to mount a volume
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Execute skywalking-eyes check of licenses
          command: |
            docker run --rm -v $(pwd):/github/workspace apache/skywalking-eyes header check
  build_docker:
    environment:
      IMAGE_NAME: quay.io/wtsicgp/annotatevcf
    machine:
      # need machine as want to copy from
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            set -e
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
            CLEAN_BRANCH=$(echo $BRANCH_OR_TAG | tr / -)
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            echo "$QUAYIO_PASSWORD" | docker login -u "$QUAYIO_USER" --password-stdin quay.io
            docker build -t $IMAGE_NAME:$CLEAN_BRANCH .
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH annotateVcf --version
            mkdir -p test-results/pytest/
            container_id=$(docker run -d --rm $IMAGE_NAME:$CLEAN_BRANCH annotateVcf sleep 1000)
            container_id=$(docker run -d --rm $IMAGE_NAME:$CLEAN_BRANCH bcftools sleep 1000)
            container_id=$(docker run -d --rm $IMAGE_NAME:$CLEAN_BRANCH tabix sleep 1000)
            docker rm -f $container_id
      - store_test_results:
          path: test-results

workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - license_chk:
          filters:
            tags:
              only: /.+/
      - build_docker:
          context:
            - dockerhub-casmservice
            - quayio-casmservice
